/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 runback.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/runback.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.runback.stop();
  })

  return (
    <group position={[-2,-3,16]} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch03001" geometry={nodes.Ch03001.geometry} material={materials['Ch03_Body.002']} skeleton={nodes.Ch03001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/runback.glb')
