/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Tire.glb --shadows 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Tire.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.001']} scale={[1.619, 1.619, 2.827]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tire.glb')
