/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Clownfish.glb 
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useGraph } from "@react-three/fiber"
import { SkeletonUtils } from "three-stdlib"

export default function Model(props) {
  const group = useRef()
  const { scene, materials, animations } = useGLTF('/Clownfish.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  // // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone)

  const { ref, actions, names } = useAnimations(animations,group)
  
  useEffect(() => {
    actions.clownfishAnim.play()  
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="clownfish" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <primitive object={nodes.Bone01} />
          <primitive object={nodes.Bone14} />
          <primitive object={nodes.Bone16} />
          <skinnedMesh name="Cylinder01" geometry={nodes.Cylinder01.geometry} material={materials['clownfish_01___Default.001']} skeleton={nodes.Cylinder01.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Clownfish.glb')
