/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 YellowBoxfish.glb 
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useGraph } from "@react-three/fiber"
import { SkeletonUtils } from "three-stdlib"

export default function Model(props) {
  const group = useRef()
  const { scene, materials, animations } = useGLTF('/YellowBoxfish.glb')
// // Skinned meshes cannot be re-used in threejs without cloning them
const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
// // useGraph creates two flat object collections for nodes and materials
const { nodes } = useGraph(clone)

const { ref, actions, names } = useAnimations(animations,group)

useEffect(() => {
  actions.yellowBoxFishAnim.play()  
}, [])  

return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="yellow_boxfish" rotation={[Math.PI / 2, 0, 0]} scale={0.0015}>
          <primitive object={nodes.Bone01} />
          <primitive object={nodes.Bone19} />
          <primitive object={nodes.Bone21} />
          <skinnedMesh name="objRetopoObject1" geometry={nodes.objRetopoObject1.geometry} material={materials.yellow_boxfish_RetopoSurface1} skeleton={nodes.objRetopoObject1.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/YellowBoxfish.glb')
